routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout.get');

Route::group(['prefix' => 'admin', 'middleware' =>['auth', 'check.role']], function () {

    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::any('images/upload', 'ImageController@ajaxUpload')->name('image.upload');
    Route::get('generate_slug', 'ServiceController@generateSlug')->name('generate.slug');
    Route::post('set_tag', 'ServiceController@setTag')->name('set.tag');

    Route::get('users/{id}/restore', 'UserController@restore')->name('users.restore');
    Route::get('users/{id}/delete', 'UserController@destroy')->name('users.delete');
    Route::resource('users', 'UserController');

    Route::get('categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
    Route::get('categories/{id}/delete', 'CategoryController@destroy')->name('categories.delete');
    Route::resource('categories', 'CategoryController');

    Route::get('posts/{id}/restore', 'PostController@restore')->name('posts.restore');
    Route::get('posts/{id}/delete', 'PostController@destroy')->name('posts.delete');
    Route::resource('posts', 'PostController');

    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/settings', 'SettingsController@update')->name('settings.update');

    Route::get('/menus', 'MenuController@index')->name('menus.index');
    Route::post('/menus/{id}', 'MenuController@update')->name('menus.update');



    Route::group(['namespace' => 'Shop'], function () {

        Route::get('orders/{id}/restore', 'OrderController@restore')->name('orders.restore');
        Route::get('orders/{id}/delete', 'OrderController@destroy')->name('orders.delete');
        Route::post('orders/update_status', 'OrderController@updateStatus')->name('orders.update.status');
        Route::resource('orders', 'OrderController');

        Route::post('products/change_status', 'ProductController@changeStatus')->name('products.status-change');
        Route::post('products/change_sold', 'ProductController@changeSold')->name('products.sold-change');
        Route::post('products/change_top', 'ProductController@changeTop')->name('products.top-change');
        Route::get('products/{id}/restore', 'ProductController@restore')->name('products.restore');
        Route::get('products/{id}/delete', 'ProductController@destroy')->name('products.delete');
        Route::resource('products', 'ProductController');

        Route::get('product_categories/{id}/restore', 'ProductCategoryController@restore')->name('product_categories.restore');
        Route::get('product_categories/{id}/delete', 'ProductCategoryController@destroy')->name('product_categories.delete');
        Route::resource('product_categories', 'ProductCategoryController');

    });


});

Route::get('/','FrontController@getHomepage')->name('homepage');
Route::get('/cart','FrontController@getCart')->name('cart');
Route::get('/account','FrontController@getCabinet')->name('cabinet')->middleware('auth');
Route::post('/create_cart', 'Shop\OrderController@createCartOrder')->name('cart.create');
Route::post('/get_cart', 'Shop\OrderController@getCartOrder')->name('cart.get');
Route::get('/get_cart_products', 'Shop\OrderController@getCartProducts')->name('cart.get.products');
Route::post('/update_cart_items', 'Shop\OrderController@updateOrderItems')->name('cart.change.products');
Route::post('/confirm_order', 'Shop\OrderController@confirmOrder')->name('cart.confirm');
Route::get('/get_products', 'Shop\ProductController@getProductsJSON')->name('products.get');
Route::get('/pages/{pages?}','FrontController@getPage')->where('pages', '.*')->name('page');
Route::get('/catalog/tags/{slug}','FrontController@getTag')->name('product.tags');
Route::get('/catalog/{products?}','FrontController@getShopPage')->where('products', '.*')->name('products.categories');

app/Models/Shop/Product.php
<?php

namespace App\Models\Shop;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Product extends Model
{
    use SoftDeletes;

    protected $guarded = ['sales','categories', 'image', 'form_type','gallery','img_delete'];

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function categories()
    {
        return $this->belongsToMany('App\Models\Shop\ProductCategory','product_category_product');
    }

    public function images()
    {
        return $this->morphMany('App\Models\Image', 'parent');
    }

    public function miniature()
    {
        return $this->images()->where('type', 'miniature')->first();
    }

    public function gallery()
    {
        return $this->images()->where('type', 'gallery')->get();
    }
    public function getReadableStatus()
    {
        $status = null;
        if (!is_null($this->deleted_at)) {
            $status = 'В корзине';
        } else {
            switch ($this->status) {
                case 'hidden':
                    $status = 'Черновик';
                    break;
                case 'published':
                    $status = 'Опубликовано';
                    break;
            }
        }
        return $status;
    }
}

app/Http/Controllers/Shop/ProductController.php
<?php

namespace App\Http\Controllers\Shop;

use App\Http\Controllers\ImageController;
use App\Models\Shop\Order;
use App\Models\Shop\Product;
use App\Models\Shop\ProductCategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->has('trashed')) {
            $products = Product::onlyTrashed();
        } else {
            $products = Product::whereNotNull('user_id');
        }

        if (isset($request->status)) {
            $products->where('status', $request->status);
        }

        if (isset($request->category)) {

            $products = Product::WhereHas('categories', function ($query) use ($request) {
                $query->where('slug', 'LIKE', $request->category);
            });
        }

        if (isset($request->user_id)) {
            $products->where('user_id', $request->user_id);
        }

        $categories = ProductCategory::withTrashed()->where('type', 'category')->get();
        return view('admin.shop.pages.products.list', [

            'products' => $products->paginate(50),
            'categories' => $categories,
            'title' => ' | Список товаров',
            'tags' => ProductCategory::where('type', 'tag')->where('parent_id', null)->where('name', '<>', null)->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $request['user_id'] = Auth::user()->id;
        $product = new Product($request->all());
        $product->id = 0;

        return view('admin.shop.pages.products.form', [
            'product' => $product,
            'title' => '| Создание товара',
            'product_categories' => ProductCategory::where('type', 'category')->where('parent_id', null)->where('name', '<>', null)->get(),
            'product_tags' => ProductCategory::where('type', 'tag')->where('parent_id', null)->where('name', '<>', null)->get(),
            'active' => 'Новый товар'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = new Product();
        $product->name = $request->name;
        $product->user_id = Auth::user()->id;
        $product->save();
        return Response($product->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::withTrashed()->where('id', $id)->first();

        return view('admin.shop.pages.products.form', [
            'product' => $product,
            'title' => '| Редактирование товара | ' . $product->name,
            'product_categories' => ProductCategory::where('type', 'category')->where('parent_id', null)->where('name', '<>', null)->get(),
            'product_tags' => ProductCategory::where('type', 'tag')->where('parent_id', null)->where('name', '<>', null)->get(),
            'active' => $product->name ? $product->name : 'Новый товар'
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::withTrashed()->where('id', $id)->first();
        $product->fill($request->all());

        $product->categories()->sync($request->categories);

        if (isset($request->image)) {
            if ($product->miniature()) {
                ImageController::deleteImage($product->miniature()->id);
            }
            ImageController::uploadImage('miniature', 'product', $id, $request->image);
        }

        if (isset($request->gallery)) {
            ImageController::massiveUpload($request, 'gallery', 'gallery', 'product', $id);
        }

        if (isset($request->img_delete)) {
            ImageController::massiveDelete($request->img_delete);
        }

        $product->save();

        return redirect(route('products.edit', $product->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return String
     */
    public function destroy($id)
    {
        $product = Product::withTrashed()->where('id', $id)->first();
        if ($product->trashed()) {
            $product->forceDelete();
        } else {
            $product->delete();
        }
        return "ok";
    }

    /**
     * Restore deleted post.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        $product = Product::withTrashed()->where('id', $id)->first();
        $product->restore();
        return Redirect::back();
    }


    //public function getProductsJSON(Request $request)
    public function getProductsJSON()
    {
        /*$cart_products = [];
        $order = Order::find($request->params['order_id']);
        $cart = json_decode($order->content, true);
        if ($cart != null) {
            foreach ($cart as $product) {
                $cart_products[] = $product->number;
            }

        }*/

        $products = Product::with(['images' => function ($query) {
            $query->where('type', 'miniature');
        }])->take(5);
        /*
                if($cart != null) {
                    $products->whereIn('id', $cart_products, 'or');
                }*/

        $products->get();

        return $products;
    }

    public function changeStatus(Request $request)
    {
        $entity = Product::find($request->id);
        if ($entity->status == 'public') {
            $entity->status = 'hidden';
        } else {
            $entity->status = 'public';
        }
        if ($entity->save()) {
            return "success";
        }
    }

    public function changeSold(Request $request)
    {
        $entity = Product::find($request->id);
        if ($entity->sold == 1) {
            $entity->sold = 0;
        } else {
            $entity->sold = 1;
        }
        if ($entity->save()) {
            return "success";
        }
    }

    public function changeTop(Request $request)
    {
        $entity = Product::find($request->id);
        if ($entity->top == 1) {
            $entity->top = 0;
        } else {
            $entity->top = 1;
        }
        if ($entity->save()) {
            return "success";
        }
    }
}

resources/views/admin/shop/pages/products/list.blade.php
@extends('admin.index')
@section('styles')
@endsection
@section('content')

    <div class="container-fluid">

        <!-- Title -->
        <div class="row heading-bg">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h5 class="txt-dark">Cписок товаров</h5>
                @if(request()->has('trashed'))
                    <a href="{{route('products.index')}}" class="ml-5">К
                        опубликованному</a>
                @else
                    <a href="{{route('products.index')}}?trashed" class="ml-5">В
                        корзину</a>
                @endif
            </div>
            @component('admin.components.breadcrumbs')
                @slot('active')Товары@endslot
            @endcomponent
        </div>
        <!-- /Title -->

        <div class="row">

            <!-- Bordered Table -->
            <div class="col-sm-12">
                <div class="panel panel-default card-view">
                    <div class="panel-wrapper collapse in">
                        <div class="panel-heading">
                            <div class="pull-left">
                                <!--TODO: вынести фильтр в отдельный компонент. А лучше - использовать один компонент для всех сущностей -->
                                <form action="" method="get">
                                    <div class="row">
                                        <div class="col-xs-6 pl-0">
                                            <select name="category" class="form-control">
                                                <option value="">Все</option>
                                                @foreach($categories as $category)
                                                    <option value="{{$category->slug}}"
                                                            @if(request()->category == $category->slug) selected @endif>{{$category->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>

                                        <div class="col-xs-2">
                                            <button class="btn btn-primary" type="submit">Показать</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="panel-body">
                            <div class="table-wrap">
                                <div class="table-responsive">
                                    <table class="table table-hover table-bordered mb-0">
                                        <thead>
                                        <tr>
                                            <th style="width:64px;">
                                                <div class="text-center"><i class="zmdi zmdi-image"></i></div>
                                            </th>
                                            <th>Название</th>
                                            <th>Категории</th>
                                            <th>Теги</th>
                                            <th class="text-nowrap">Действия</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($products as $product )
                                            <tr data-id="{{$product->id}}">
                                                <td style="width:64px;">
                                                    <a href="{{route('products.edit', $product->id)}}">
                                                        @if(is_object($product->miniature()))
                                                            <img src="{{$product->miniature()->thumbnail}}" alt=""
                                                                 height="32">
                                                        @else
                                                            <img src="http://via.placeholder.com/32x32" alt="">
                                                        @endif
                                                    </a>
                                                </td>
                                                <td>
                                                    <a href="{{route('products.edit', $product->id)}}">{{is_null($product->name)?'Новый товар': $product->name}}</a>
                                                </td>

                                                <td>@foreach($product->categories->where('type', 'category') as $cat)
                                                        <a href="{{route('product_categories.edit', $cat->id)}}">{{$cat->name}}</a>
                                                    @endforeach
                                                </td>
                                                <td>
                                                    <select data-placeholder="Выберите тег" class="chosen-select"
                                                            data-product="{{$product->id}}" multiple>
                                                        @foreach($tags as $tag)
                                                            <option value="{{$tag->id}}"
                                                                    @if($product->categories->contains($tag->id))
                                                                    selected
                                                                    @endif>{{$tag->name}}</option>
                                                        @endforeach
                                                    </select>
                                                </td>
                                                <td class="text-nowrap">

                                                    <a href="#!" data-toggle="tooltip" class="mr-10 ="
                                                       data-original-title="Популярность товара">
                                                        <i class="fa {{ $product->top == 1 ?"fa-star":"fa-star-half"}} site-top-button"></i>
                                                    </a>

                                                    <a href="#!" data-toggle="tooltip" class="mr-10 ="
                                                       data-original-title="Видимость на сайте">
                                                        <i class="fa {{ $product->status == "public"?"fa-eye":"fa-eye-slash"}} site-visible-button"></i>
                                                    </a>

                                                    <a href="#!" data-toggle="tooltip" class="mr-10 ="
                                                       data-original-title="Доступность для покупки">
                                                        <i class="fa {{ $product->sold == 1 ?"fa-lock":"fa-unlock"}} site-available-button"></i>
                                                    </a>

                                                    <a href="{{route('products.edit', $product->id)}}" class="mr-10"
                                                       data-toggle="tooltip" data-original-title="Редактировать"> <i
                                                                class="fa fa-pencil text-inverse"></i> </a>
                                                    <a href="#" data-toggle="tooltip" class="mr-10"
                                                       data-original-title="Удалить"><i
                                                                class="fa fa-close btn-modal-close text-danger"></i></a>
                                                    @if(!is_null($product->deleted_at))
                                                        <a href="#" data-toggle="tooltip" class="mr-10"
                                                           data-original-title="Восстановить"> <i
                                                                    class="fa fa-arrow-up btn-modal-restore text-success"></i>
                                                        </a>
                                                    @endif
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="text-center">
                                {!! $products->render()!!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Bordered Table -->

        </div>

    </div>
@endsection

@component('admin.components.modal_delete')
    @slot('modal_text') {{!request()->has('trashed') ? 'убрать товар в корзину': 'окончательно удалить товар'}}  @endslot
    @slot('modal_caption') {{!request()->has('trashed') ? 'Убрать': 'Удалить'}} @endslot
@endcomponent

@if(request()->has('trashed'))
    @component('admin.components.modal_restore')
        @slot('modal_target') товар @endslot
    @endcomponent
@endif
@section('scripts')
    <script>
        $(".chosen-select").chosen({
            width: "100%",
        }).on('change', function (evt, params) {
            console.log();
            params.id = $(evt.target).data('product');
            params.type = "App\\Models\\Shop\\Product";
            params._token = "{{csrf_token()}}";
            $.post("{{route('set.tag')}}", params, function (data) {

            });
        });

        $(".btn-modal-close").click('change',function () {

            var product_row = $(this).closest('tr');
            var id = product_row.data('id');
            console.log(id);
            $("#delModal").modal();

            $(".btn-del").click(function () {

                $.get("/admin/products/" + id + "/delete  ", function (data) {
                    if(data === "ok") {
                        product_row.fadeOut(500);
                    }
                });
            });
        });

        $(".btn-modal-restore").click(function () {
            var id = $(this).closest('tr').data('id');
            $("#restoreModal").modal();
            $(".btn-rest").click(function () {
                window.location.href = "/admin/products/" + id + "/restore";
            });
        });

        $(".site-visible-button").click(function () {
            event.preventDefault();
            var button = $(this);
            var id = button.closest('tr').data('id');
            $.post("{{route('products.status-change')}}", {
                id: id,
                _token: "{{csrf_token()}}"
            }, function (data) {
                if(data === "success") {
                    if(button.hasClass('fa-eye')) {
                        button.removeClass('fa-eye').addClass('fa-eye-slash');
                    } else {
                        button.removeClass('fa-eye-slash').addClass('fa-eye');
                    }
                }
            });
        });

        $(".site-available-button").click(function () {
            event.preventDefault();
            var button = $(this);
            var id = button.closest('tr').data('id');
            $.post("{{route('products.sold-change')}}", {
                id: id,
                _token: "{{csrf_token()}}"
            }, function (data) {
                if(data === "success") {
                    if(button.hasClass('fa-lock')) {
                        button.removeClass('fa-lock').addClass('fa-unlock');
                    } else {
                        button.removeClass('fa-unlock').addClass('fa-lock');
                    }
                }
            });
        });

        $(".site-top-button").click(function () {
            event.preventDefault();
            var button = $(this);
            var id = button.closest('tr').data('id');
            $.post("{{route('products.top-change')}}", {
                id: id,
                _token: "{{csrf_token()}}"
            }, function (data) {
                if(data === "success") {
                    if(button.hasClass('fa-star-half')) {
                        button.removeClass('fa-star-half').addClass('fa-star');
                    } else {
                        button.removeClass('fa-star').addClass('fa-star-half');
                    }
                }
            });
        });
    </script>

@endsection