routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout.get');

Route::group(['prefix' => 'admin', 'middleware' =>['auth', 'check.role']], function () {

    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::any('images/upload', 'ImageController@ajaxUpload')->name('image.upload');
    Route::get('generate_slug', 'ServiceController@generateSlug')->name('generate.slug');
    Route::post('set_tag', 'ServiceController@setTag')->name('set.tag');

    Route::get('users/{id}/restore', 'UserController@restore')->name('users.restore');
    Route::get('users/{id}/delete', 'UserController@destroy')->name('users.delete');
    Route::resource('users', 'UserController');

    Route::get('categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
    Route::get('categories/{id}/delete', 'CategoryController@destroy')->name('categories.delete');
    Route::resource('categories', 'CategoryController');

    Route::get('posts/{id}/restore', 'PostController@restore')->name('posts.restore');
    Route::get('posts/{id}/delete', 'PostController@destroy')->name('posts.delete');
    Route::resource('posts', 'PostController');

    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/settings', 'SettingsController@update')->name('settings.update');

    Route::get('/menus', 'MenuController@index')->name('menus.index');
    Route::post('/menus/{id}', 'MenuController@update')->name('menus.update');



    Route::group(['namespace' => 'Shop'], function () {

        Route::get('orders/{id}/restore', 'OrderController@restore')->name('orders.restore');
        Route::get('orders/{id}/delete', 'OrderController@destroy')->name('orders.delete');
        Route::post('orders/update_status', 'OrderController@updateStatus')->name('orders.update.status');
        Route::resource('orders', 'OrderController');

        Route::post('products/change_status', 'ProductController@changeStatus')->name('products.status-change');
        Route::post('products/change_sold', 'ProductController@changeSold')->name('products.sold-change');
        Route::post('products/change_top', 'ProductController@changeTop')->name('products.top-change');
        Route::get('products/{id}/restore', 'ProductController@restore')->name('products.restore');
        Route::get('products/{id}/delete', 'ProductController@destroy')->name('products.delete');
        Route::resource('products', 'ProductController');

        Route::get('product_categories/{id}/restore', 'ProductCategoryController@restore')->name('product_categories.restore');
        Route::get('product_categories/{id}/delete', 'ProductCategoryController@destroy')->name('product_categories.delete');
        Route::resource('product_categories', 'ProductCategoryController');

    });


});

Route::get('/','FrontController@getHomepage')->name('homepage');
Route::get('/cart','FrontController@getCart')->name('cart');
Route::get('/account','FrontController@getCabinet')->name('cabinet')->middleware('auth');
Route::post('/create_cart', 'Shop\OrderController@createCartOrder')->name('cart.create');
Route::post('/get_cart', 'Shop\OrderController@getCartOrder')->name('cart.get');
Route::get('/get_cart_products', 'Shop\OrderController@getCartProducts')->name('cart.get.products');
Route::post('/update_cart_items', 'Shop\OrderController@updateOrderItems')->name('cart.change.products');
Route::post('/confirm_order', 'Shop\OrderController@confirmOrder')->name('cart.confirm');
Route::get('/get_products', 'Shop\ProductController@getProductsJSON')->name('products.get');
Route::get('/pages/{pages?}','FrontController@getPage')->where('pages', '.*')->name('page');
Route::get('/catalog/tags/{slug}','FrontController@getTag')->name('product.tags');
Route::get('/catalog/{products?}','FrontController@getShopPage')->where('products', '.*')->name('products.categories');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role()
    {
        return $this->belongsTo('App\Models\Role');
    }

    public function orders()
    {
        return $this->hasMany('App\Models\Shop\Order');
    }

    public function images()
    {
        return $this->morphMany('App\Models\Image', 'parent');
    }

    public function miniature()
    {
        return $this->images()->where('type', 'miniature')->first();
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Response;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->has('trashed')) {
            $users = User::onlyTrashed();
        } else {
            $users = User::whereNotNull('role_id');
        }

        if (isset($request->role_id)) {
            $users->where('role_id', $request->role_id);
        }


        return view('admin.pages.users.list', [
            'users' => $users->get(),
            'title'  => ' | Список пользователей',
            'active' => 'Пользователи'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User();
        $user->id = 0;
        return view('admin.pages.users.form', [
            'user' => $user,
            'roles' => Role::all(),
            'title'  => ' | Создание пользователя',
            'active' => 'Новый пользователь'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = new User();
        $user->name = $request->name;
        $user->save();
        return Response($user->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::withTrashed()->where('id', $id)->first();

        return view('admin.pages.users.form', [
            'user' => $user,
            'roles' => Role::all(),
            'title' => '| Редактирование пользователя | '. $user->name,
            'active' => $user->name ? $user->name : 'Новый пользователь'
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::withTrashed()->where('id', $id)->first();

        if(!is_null($request->password) && $request->password == $request->password_repeat) {
            $user->password = bcrypt($request->password);
            unset($request['password']);
        } else {
            unset($request['password']);
        }
        $user->fill($request->all());


        if(isset($request->image)){
            if($user->miniature()) {
                ImageController::deleteImage($user->miniature()->id);
            }
            ImageController::uploadImage('miniature', 'user', $id, $request->image);
        }
        $user->save();

        return Redirect::back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::withTrashed()->where('id', $id)->first();

        if ($user->trashed()) {
            $user->forceDelete();
            return redirect(route('users.index'));
        } else {
            $user->delete();
            return Redirect::back();
        }
    }

    /**
     * Restore deleted post.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        $user = User::withTrashed()->where('id', $id)->first();
        $user->restore();
        return Redirect::back();
    }
}

resources/views/admin/pages/users/form.blade.php
@extends('admin.index')
@section('styles')
    <!-- Summernote css -->
    <link rel="stylesheet" href="/admin-files/vendors/bower_components/summernote/dist/summernote.css"/>
@endsection
@section('content')

    <div class="container-fluid">

        <!-- Title -->
        <div class="row heading-bg">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h5 class="txt-dark">Редактирование пользователя</h5>
            </div>
            <!-- TODO: Trello -REFRACT FOR USING POLICIES -->
            @component('admin.components.breadcrumbs')
                @if(!in_array(Auth::user()->role->role,['user', 'shop_manager']))
                    @slot('parent_route') {{route('users.index')}} @endslot
                    @slot('parent') Пользователи @endslot
                @endif
                @slot('active') {{$active}} @endslot
            @endcomponent

        </div>
        <!-- /Title -->

        <!-- Row -->
        <div class="row">
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default card-view">
                            <div class="panel-heading">
                                <a role="button" data-toggle="collapse" href="#collapsePost" aria-expanded="true"
                                   aria-controls="collapsePost" class="d-block">
                                    <h6 class="panel-title txt-dark">Редактор</h6>
                                </a>
                            </div>
                            <div class="panel-wrapper collapse in" id="collapsePost">
                                <div class="panel-body">
                                    <div class="form-wrap mt-10">
                                        <form name="form-data" id="form-data" enctype="multipart/form-data"
                                              action="{{route('users.update', $user->id)}}"
                                              method="POST">
                                            <div class="form-group">
                                                <label class="control-label mb-10 text-left">Имя пользователя</label>
                                                <input type="text" class="form-control" value="{{$user->name}}"
                                                       name="name"
                                                       placeholder="Новый пользователь">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label mb-10 text-left">Email</label>
                                                <input type="email" class="form-control" value="{{$user->email}}"
                                                       name="email"
                                                       placeholder="user@example.com">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label mb-10 text-left">Пароль</label>
                                                <input type="password" class="form-control"
                                                       name="password">
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label mb-10 text-left">Подтверждение
                                                    пароля</label>
                                                <input type="password" class="form-control"
                                                       name="password_repeat">
                                            </div>

                                            <!-- TODO: Trello - REFRACT FOR USING POLICIES -->
                                            @if(!in_array(Auth::user()->role->role,['user', 'shop_manager']))
                                                <div class="form-group">
                                                    <select name="role_id" id="">
                                                        @foreach($roles as $role)
                                                            <option value="{{$role->id}}"
                                                                    @if($user->role_id == $role->id) selected @endif>{{$role->role_name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            @endif
                                            <input type="hidden" name="id" value="{{$user->id}}">
                                            @method('PUT')
                                            @csrf
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="row">
                    @component('admin.components.blocks.control_block',
                    ['deleted_at' => $user->deleted_at])
                        @slot('created_at') {{$user->created_at}} @endslot
                        @slot('status') '' @endslot
                    @endcomponent

                    @component('admin.components.blocks.miniature_block',
                    ['miniature' => $user->miniature(), 'id' => $user->id])
                    @endcomponent
                </div>
            </div>

            <!-- /Row -->


        </div>
        @endsection

        @component('admin.components.modal_delete')
            @slot('modal_text') {{is_null($user->deleted_at)? 'убрать пользователя в корзину': 'окончательно удалить пользователя'}}  @endslot
            @slot('modal_caption') {{is_null($user->deleted_at)? 'Убрать': 'Удалить'}} @endslot
        @endcomponent
        @if(!is_null($user->deleted_at))
            @component('admin.components.modal_restore')
                @slot('modal_target') пользователя @endslot
            @endcomponent
        @endif
        @section('scripts')
            <script>
                $(".btn-del").click(function () {
                    window.location.href = "/admin/users/" + $('input[name="id"]').val() + "/delete";
                });
                $(".btn-rest").click(function () {
                    window.location.href = "/admin/users/" + $('input[name="id"]').val() + "/restore";
                });

                $('input[name="name"]').blur(function () {
                    if ($('input[name="id"]').val() === "0") {

                        $.post("{{route('users.store')}}", {
                            _token: "{{csrf_token()}}",
                            name: $('input[name="name"]').val(),

                        }, function (data) {
                            $('input[name="id"]').val(data);
                            $('input[name="image"]').prop("disabled", false);
                            $('#form-data').attr("action", "/admin/users/" + data);
                        });
                    }
                });
            </script>

@endsection

resources/views/admin/pages/users/list.blade.php
@extends('admin.index')
@section('styles')
@endsection
@section('content')

    <div class="container-fluid">

        <!-- Title -->
        <div class="row heading-bg">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h5 class="txt-dark">Cписок пользователей</h5>
                @if(request()->has('trashed'))
                    <a href="{{route('users.index')}}" class="ml-5">К
                        активным</a>
                @else
                    <a href="{{route('users.index')}}?trashed" class="ml-5">В
                        корзину</a>
                @endif
            </div>
            @component('admin.components.breadcrumbs')
                @slot('active') {{$active}} @endslot
            @endcomponent
        </div>
        <!-- /Title -->

        <div class="row">

            <!-- Bordered Table -->
            <div class="col-sm-12">
                <div class="panel panel-default card-view">
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">

                            <div class="table-wrap">
                                <div class="table-responsive">
                                    <table class="table table-hover table-bordered mb-0">
                                        <thead>
                                        <tr>
                                            <th>Имя</th>
                                            <th>Роль</th>
                                            <th>Зарегистрировался</th>
                                            <th class="text-nowrap">Действия</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($users as $user )
                                            <tr data-id="{{$user->id}}">
                                                <td>
                                                    <a href="{{route('users.edit', $user->id)}}">{{is_null($user->name)?'Новый пользователь': $user->name}}</a>
                                                </td>
                                                <td>{{$user->role->role_name}}</td>
                                                <td>{{$user->created_at}}</td>
                                                <td class="text-nowrap">
                                                    <a href="{{route('users.edit', $user->id)}}" class="mr-10"
                                                       data-toggle="tooltip" data-original-title="Редактировать"> <i
                                                                class="fa fa-pencil text-inverse"></i> </a>
                                                    <a href="#" data-toggle="tooltip" class="mr-10"
                                                       data-original-title="Убрать"> <i
                                                                class="fa fa-close btn-modal-close text-danger"></i>
                                                    </a>
                                                    @if(!is_null($user->deleted_at))
                                                        <a href="#" data-toggle="tooltip" class="mr-10"
                                                           data-original-title="Восстановить"> <i
                                                                    class="fa fa-arrow-up btn-modal-restore text-success"></i>
                                                        </a>
                                                    @endif
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Bordered Table -->

        </div>

    </div>
@endsection

@component('admin.components.modal_delete')
    @slot('modal_text') {{!request()->has('trashed') ? 'убрать пользователя в корзину': 'окончательно удалить пользователя'}}  @endslot
    @slot('modal_caption') {{!request()->has('trashed') ? 'Убрать': 'Удалить'}} @endslot
@endcomponent

@if(request()->has('trashed'))
    @component('admin.components.modal_restore')
        @slot('modal_target') пользователя @endslot
    @endcomponent
@endif
@section('scripts')
    <script>
        $(".btn-modal-close").click(function () {
            var id = $(this).closest('tr').data('id');
            console.log(id);
            $("#delModal").modal();
            $(".btn-del").click(function () {
                window.location.href = "/admin/users/" + id + "/delete  ";
            });
        });

        $(".btn-modal-restore").click(function () {
            var id = $(this).closest('tr').data('id');
            console.log(id);
            $("#restoreModal").modal();
            $(".btn-rest").click(function () {
                window.location.href = "/admin/users/" + id + "/restore";
            });
        });
    </script>


@endsection