routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout.get');

Route::group(['prefix' => 'admin', 'middleware' =>['auth', 'check.role']], function () {

    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::any('images/upload', 'ImageController@ajaxUpload')->name('image.upload');
    Route::get('generate_slug', 'ServiceController@generateSlug')->name('generate.slug');
    Route::post('set_tag', 'ServiceController@setTag')->name('set.tag');

    Route::get('users/{id}/restore', 'UserController@restore')->name('users.restore');
    Route::get('users/{id}/delete', 'UserController@destroy')->name('users.delete');
    Route::resource('users', 'UserController');

    Route::get('categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
    Route::get('categories/{id}/delete', 'CategoryController@destroy')->name('categories.delete');
    Route::resource('categories', 'CategoryController');

    Route::get('posts/{id}/restore', 'PostController@restore')->name('posts.restore');
    Route::get('posts/{id}/delete', 'PostController@destroy')->name('posts.delete');
    Route::resource('posts', 'PostController');

    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/settings', 'SettingsController@update')->name('settings.update');

    Route::get('/menus', 'MenuController@index')->name('menus.index');
    Route::post('/menus/{id}', 'MenuController@update')->name('menus.update');



    Route::group(['namespace' => 'Shop'], function () {

        Route::get('orders/{id}/restore', 'OrderController@restore')->name('orders.restore');
        Route::get('orders/{id}/delete', 'OrderController@destroy')->name('orders.delete');
        Route::post('orders/update_status', 'OrderController@updateStatus')->name('orders.update.status');
        Route::resource('orders', 'OrderController');

        Route::post('products/change_status', 'ProductController@changeStatus')->name('products.status-change');
        Route::post('products/change_sold', 'ProductController@changeSold')->name('products.sold-change');
        Route::post('products/change_top', 'ProductController@changeTop')->name('products.top-change');
        Route::get('products/{id}/restore', 'ProductController@restore')->name('products.restore');
        Route::get('products/{id}/delete', 'ProductController@destroy')->name('products.delete');
        Route::resource('products', 'ProductController');

        Route::get('product_categories/{id}/restore', 'ProductCategoryController@restore')->name('product_categories.restore');
        Route::get('product_categories/{id}/delete', 'ProductCategoryController@destroy')->name('product_categories.delete');
        Route::resource('product_categories', 'ProductCategoryController');

    });


});

Route::get('/','FrontController@getHomepage')->name('homepage');
Route::get('/cart','FrontController@getCart')->name('cart');
Route::get('/account','FrontController@getCabinet')->name('cabinet')->middleware('auth');
Route::post('/create_cart', 'Shop\OrderController@createCartOrder')->name('cart.create');
Route::post('/get_cart', 'Shop\OrderController@getCartOrder')->name('cart.get');
Route::get('/get_cart_products', 'Shop\OrderController@getCartProducts')->name('cart.get.products');
Route::post('/update_cart_items', 'Shop\OrderController@updateOrderItems')->name('cart.change.products');
Route::post('/confirm_order', 'Shop\OrderController@confirmOrder')->name('cart.confirm');
Route::get('/get_products', 'Shop\ProductController@getProductsJSON')->name('products.get');
Route::get('/pages/{pages?}','FrontController@getPage')->where('pages', '.*')->name('page');
Route::get('/catalog/tags/{slug}','FrontController@getTag')->name('product.tags');
Route::get('/catalog/{products?}','FrontController@getShopPage')->where('products', '.*')->name('products.categories');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    protected $fillable = ['type', 'status', 'name', 'slug', 'caption', 'parent_id', 'user_id', 'description', 'keywords'];

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function posts()
    {
        return $this->belongsToMany('App\Models\Post');
    }

    public function parent()
    {
        return $this->belongsTo('App\Models\Category', 'parent_id', 'id');
    }

    public function children()
    {
        return $this->hasMany('App\Models\Category', 'parent_id', 'id');
    }

    public function images()
    {
        return $this->morphMany('App\Models\Image', 'parent');
    }

    public function miniature()
    {
        return $this->images()->where('type', 'miniature')->first();
    }

    public function gallery()
    {
        return $this->images()->where('type', 'gallery')->get();
    }
    public function getReadableStatus()
    {
        $status = null;
        if (!is_null($this->deleted_at)) {
            $status = 'В корзине';
        } else {
            switch ($this->status) {
                case 'hidden':
                    $status = 'Черновик';
                    break;
                case 'published':
                    $status = 'Опубликовано';
                    break;
            }
        }
        return $status;
    }

    public function getUrl()
    {
        $url = $this->slug;

        $category = $this;

        while ($category = $category->parent) {
            $url = $category->slug.'/'.$url;
        }

        return '/pages/'.$url;
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->has('trashed')) {
            $category = Category::onlyTrashed();
        } else {
            $category = Category::whereNotNull('user_id');
        }

        $category->where('type', $request->type);

        if(isset($request->status)) {
            $category->where('status', $request->status);
        }

        if(isset($request->user_id)) {
            $category->where('user_id', $request->user_id);
        }

        $category->where('parent_id', null);
        
        return view('admin.pages.categories.list',[
            'categories' => $category->get(),
            'title' => ' | Список категорий',
            'active' => 'Категории'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $request['user_id'] = Auth::user()->id;
        $category = new Category($request->all());
        $category->id = 0;
        $category->type = $request->type;
        return view('admin.pages.categories.form',[
            'category' => $category,
            'title' => '| Создание категории',
            'categories' => Category::whereNotIn('id', [$category->id])->where('name', '<>', null)->get(),
            'active' => 'Создание'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = new Category();
        $category->name = $request->name;
        $category->type = $request->type;
        $category->user_id = Auth::user()->id;
        $category->save();
        return Response($category->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::withTrashed()->where('id', $id)->first();

        return view('admin.pages.categories.form',[
            'category' => $category,
            'title' => '| Редактирование категории | '. $category->name,
            'categories' => Category::whereNotIn('id', [$id])->where('name', '<>', null)->get(),
            'active' => $category->name ? $category->name : 'Новая категория'
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::withTrashed()->where('id', $id)->first();
        $category->fill($request->all());

        if(isset($request->image)){
            if($category->miniature()) {
                ImageController::deleteImage($category->miniature()->id);
            }
            ImageController::uploadImage( 'miniature', 'category', $id, $request->image);
        }

        if(isset($request->gallery)){
            ImageController::massiveUpload($request, 'gallery', 'gallery','category', $id);
        }

        if(isset($request->img_delete)){
            ImageController::massiveDelete($request->img_delete);
        }

        $category->save();

        return redirect(route('categories.edit', $category->id));
    }

    public function destroy($id)
    {
        $category = Category::withTrashed()->where('id', $id)->first();
        $type = $category->type;
        if ($category->trashed()) {
            $category->forceDelete();
            return redirect(route('categories.index', ['type' => $type]));
        } else {
            $category->delete();
            return Redirect::back();
        }
    }

    /**
     * Restore deleted Category.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        $category = Category::withTrashed()->where('id', $id)->first();
        $category->restore();
        return Redirect::back();
    }
}

resources/views/admin/pages/categories/form.blade.php
@extends('admin.index')
@section('styles')
    <!-- Summernote css -->
    <link rel="stylesheet" href="/admin-files/vendors/bower_components/summernote/dist/summernote.css"/>
@endsection
@section('content')

    <div class="container-fluid">

        <!-- Title -->
        <div class="row heading-bg">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h5 class="txt-dark">Редактирование категории</h5>
            </div>

            @component('admin.components.breadcrumbs')
                @slot('parent_route') {{route('categories.index', ['type' => $category->type])}} @endslot
                @slot('parent') Категории @endslot
                @slot('active') {{$active}} @endslot
            @endcomponent

        </div>
        <!-- /Title -->

        <!-- Row -->
        <div class="row">
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default card-view">
                            <div class="panel-heading">
                                <a role="button" data-toggle="collapse" href="#collapseCategory" aria-expanded="true"
                                   aria-controls="collapseCategory" class="d-block">
                                    <h6 class="panel-title txt-dark">Редактор</h6>
                                </a>
                            </div>
                            <div class="panel-wrapper collapse in" id="collapseCategory">
                                <div class="panel-body">
                                    <div class="form-wrap mt-10">
                                        <form name="form-data" id="form-data" enctype="multipart/form-data"
                                              action="{{route('categories.update', $category->id)}}"
                                              method="POST">
                                            <div class="form-group">
                                                <label class="control-label mb-10 text-left">Название</label>
                                                <input type="text" class="form-control" value="{{$category->name}}"
                                                       name="name"
                                                       placeholder="Новая категория">
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label mb-10 text-left">Ссылка</label>
                                                <input type="text" class="form-control" value="{{$category->slug}}"
                                                       name="slug"
                                                       placeholder="new_post">
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label mb-10 text-left">Описание</label>
                                                <textarea name="caption" rows="10"
                                                          class="form-control no-resize summernote">{{$category->caption}}</textarea>
                                            </div>

                                            <div class="form-group row">
                                                <div class="col-xs-6">
                                                    <label class="control-label mb-10 text-left">Тип</label>
                                                    <select name="type" id="" class="cat-type">
                                                        <option value="category"
                                                                @if($category->type == 'category') selected @endif>
                                                            Категория
                                                        </option>
                                                        <option value="tag"
                                                                @if($category->type == 'tag') selected @endif>
                                                            Тег
                                                        </option>
                                                    </select>
                                                </div>

                                                <div class="col-xs-6 parent-selector">
                                                    <label class="control-label mb-10 text-left">Родитель</label>
                                                    <select name="parent_id" id="">
                                                        <option value=""
                                                                @if(is_null($category->parent_id)) selected @endif>
                                                            Без
                                                            родителя
                                                        </option>

                                                        @foreach($categories as $cat)
                                                            <option value="{{$cat->id}}"
                                                                    @if($category->parent_id == $cat->id) selected @endif>{{$cat->name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <input type="hidden" name="id" value="{{$category->id}}">
                                            <input type="hidden" name="user_id" value="{{$category->user_id}}">
                                            @method('PUT')
                                            @csrf
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    @component('admin.components.panels.gallery_panel',
                    ['gallery' => $category->gallery(), 'id' => $category->id])
                    @endcomponent

                    @component('admin.components.panels.seo_panel')
                        @slot('keywords') {{$category->keywords}} @endslot
                        @slot('description') {{$category->description}} @endslot
                    @endcomponent
                </div>
            </div>

            <div class="col-md-3">
                <div class="row">
                    @component('admin.components.blocks.control_block',
                    ['deleted_at' => $category->deleted_at])
                        @slot('created_at') {{$category->created_at}} @endslot
                        @slot('status') {{$category->status}} @endslot
                    @endcomponent

                    @component('admin.components.blocks.miniature_block',
                    ['miniature' => $category->miniature(), 'id' => $category->id])
                    @endcomponent

                </div>
            </div>

            <!-- /Row -->


        </div>
        <!-- /Row -->


    </div>
@endsection

@component('admin.components.modal_delete')
    @slot('modal_text') {{is_null($category->deleted_at)? 'убрать категорию в корзину': 'окончательно удалить категорию'}}  @endslot
    @slot('modal_caption') {{is_null($category->deleted_at)? 'Убрать': 'Удалить'}} @endslot
@endcomponent
@if(!is_null($category->deleted_at))
    @component('admin.components.modal_restore')
        @slot('modal_target') категорию @endslot
    @endcomponent
@endif
@section('scripts')
    <script src="/admin-files/vendors/bower_components/summernote/dist/summernote.min.js"></script>
    <script src="/admin-files/vendors/bower_components/summernote/lang/summernote-ru-RU.js"></script>
    <script>
        <!-- Summernote Plugin JavaScript -->
        $('.summernote').summernote({
            lang: 'ru-RU',
            height: 300,
            callbacks: {
                onImageUpload: function(files) {
                    var el = $(this);
                    sendFile(files[0],el);
                }
            }
        });

        function sendFile(file, el) {
            var  data = new FormData();
            data.append("image", file);
            data.append("type", 'content_image');
            data.append("parent_type", 'category');
            data.append("parent_id",  $('input[name="id"]').val());
            var url = '{{ route('image.upload') }}';
            $.ajax({
                data: data,
                type: "POST",
                headers: {'X-CSRF-TOKEN': $('input[name="_token"]').val()},
                url: url,
                cache: false,
                contentType: false,
                processData: false,
                success: function(link) {
                    el.summernote('insertImage', link);
                }
            });
        }

        $(".btn-del").click(function () {
            window.location.href = "/admin/categories/" + $('input[name="id"]').val() + "/delete";
        });
        $(".btn-rest").click(function () {
            window.location.href = "/admin/categories/" + $('input[name="id"]').val() + "/restore";
        });
        $('input[name="name"]').blur(function(){
            if($('input[name="slug"]').val().length == 0) {
                $.get("{{route('generate.slug')}}", {_token:"{{csrf_token()}}", slug_string: $('input[name="name"]').val()}, function (data) {
                    $('input[name="slug"]').val(data);
                });
            }

            if ($('input[name="id"]').val() === "0") {

                $.post("{{route('categories.store')}}", {
                    _token: "{{csrf_token()}}",
                    name: $('input[name="name"]').val(),
                    type: $('select[name="type"]').val()
                }, function (data) {
                    $('input[name="id"]').val(data);
                    $('input[name="gallery\\[\\]"]').prop("disabled", false);
                    $('input[name="image"]').prop("disabled", false);
                    $('#form-data').attr("action", "/admin/categories/" + data);

                });
            }
        });
    </script>

@endsection

resources/views/admin/pages/categories/list.blade.php
@extends('admin.index')
@section('styles')
@endsection
@section('content')

    <div class="container-fluid">

        <!-- Title -->
        <div class="row heading-bg">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h5 class="txt-dark">Cписок категорий</h5>
                @if(request()->has('trashed'))
                    <a href="{{route('categories.index', ['type'=> request()->input('type')])}}" class="ml-5">К
                        опубликованному</a>
                @else
                    <a href="{{route('categories.index', ['type'=> request()->input('type')])}}&trashed" class="ml-5">В
                        корзину</a>
                @endif
            </div>
            @component('admin.components.breadcrumbs')
                @slot('active') {{$active}} @endslot
            @endcomponent
        </div>
        <!-- /Title -->

        <div class="row">

            <!-- Bordered Table -->
            <div class="col-sm-12">
                <div class="panel panel-default card-view">
                    <div class="panel-heading">
                        <div class="pull-left">
                        @component('admin.components.paging.filter')@endcomponent
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">

                            <div class="table-wrap">
                                <div class="table-responsive">
                                    <table class="table table-hover table-bordered mb-0">
                                        <thead>
                                        <tr>
                                            <th>Название</th>
                                            <th>Дата</th>
                                            <th>Автор</th>
                                            <th class="text-nowrap">Действия</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php buildCategoriesList($categories, 'categories')?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Bordered Table -->

        </div>

    </div>
@endsection

@component('admin.components.modal_delete')
    @slot('modal_text') {{!request()->has('trashed') ? 'убрать категорию в корзину': 'окончательно удалить категорию'}}  @endslot
    @slot('modal_caption') {{!request()->has('trashed') ? 'Убрать': 'Удалить'}} @endslot
@endcomponent

@if(request()->has('trashed'))
    @component('admin.components.modal_restore')
        @slot('modal_target') категорию @endslot
    @endcomponent
@endif
@section('scripts')
    <script>
        $(".btn-modal-close").click(function () {
            var id = $(this).closest('tr').data('id');
            console.log(id);
            $("#delModal").modal();
            $(".btn-del").click(function () {
                window.location.href = "/admin/categories/" + id + "/delete  ";
            });
        });

        $(".btn-modal-restore").click(function () {
            var id = $(this).closest('tr').data('id');
            console.log(id);
            $("#restoreModal").modal();
            $(".btn-rest").click(function () {
                window.location.href = "/admin/categories/" + id + "/restore";
            });
        });
    </script>


@endsection